import type { ComponentType } from "react";
import { registerMotionComponent } from "@/components/motion/components/registry";
import type { MotionComponentProps } from "@/components/motion/components/registry";

import {
  MetricCard,
  KPITile,
  StatisticBlock,
  PricingCard,
  FeatureCard,
  BenefitCard,
  ComparisonCard,
  TestimonialCard,
  Badge,
  BrandChip,
  CTABanner,
} from "@/components/motion/components/marketing";

import {
  BrowserWindow,
  Dashboard,
  Sidebar,
  TopNavigation,
  SearchBar,
  ChatWindow,
  ChatDemo,
  AIResponse,
  Notification,
  FloatingTooltip,
  Modal,
  CommandPalette,
  SettingsPanel,
  CodeEditor,
  TerminalWindow,
} from "@/components/motion/components/ui";

import {
  iPhone,
  ClaudeMobileHome,
  AndroidPhone,
  Tablet,
  MacBook,
  Laptop,
  DesktopMonitor,
  BrowserMockup,
} from "@/components/motion/components/devices";

import {
  LogoLockup,
  Wordmark,
  IconGrid,
  TrustBadge,
  CompanyLogoRow,
  SocialProofRow,
} from "@/components/motion/components/brand";

import {
  ProductCard,
  ProductGrid,
  CheckoutScreen,
  ShoppingCart,
  ReviewCard,
  RatingStars,
  BeforeAfterComparison,
  OfferStack,
  GuaranteeBox,
} from "@/components/motion/components/commerce";

import {
  LineChart,
  BarChart,
  PieChart,
  GrowthCurve,
  Timeline,
  Funnel,
  ProgressRing,
  Counter,
  AnimatedGraph,
} from "@/components/motion/components/data";

import {
  BookCoverCarousel,
  BookCoverStream,
  CourseCarousel,
  ImageStack,
  ScreenshotGallery,
  VideoThumbnail,
  FloatingMediaWall,
} from "@/components/motion/components/media";

import {
  ParticleField,
  GradientBlob,
  AnimatedGrid,
  OrbitalLines,
  FloatingShapes,
  NoiseOverlay,
  GlowField,
  MeshGradient,
  Aurora,
  BlueprintGrid,
} from "@/components/motion/components/backgrounds";

import {
  SequentialReveal,
  StaggerGrid,
  CardStack,
  InfiniteHorizontalCarousel,
  InfiniteVerticalCarousel,
  Marquee,
  FloatingLayerGroup,
  ExplodedLayout,
  IsometricStack,
} from "@/components/motion/components/motionFx";

import { Capsule3D } from "@/components/motion/components/Capsule3D";
import { PillHero } from "@/components/motion/components/PillHero";

const REGISTRY: Record<string, ComponentType<MotionComponentProps>> = {
  MetricCard,
  KPITile,
  StatisticBlock,
  PricingCard,
  FeatureCard,
  BenefitCard,
  ComparisonCard,
  TestimonialCard,
  Badge,
  BrandChip,
  CTABanner,
  BrowserWindow,
  BrowserMockup,
  Dashboard,
  Sidebar,
  TopNavigation,
  SearchBar,
  ChatWindow,
  ChatDemo,
  AIResponse,
  Notification,
  FloatingTooltip,
  Modal,
  CommandPalette,
  SettingsPanel,
  CodeEditor,
  TerminalWindow,
  iPhone,
  ClaudeMobileHome,
  AndroidPhone,
  Tablet,
  MacBook,
  Laptop,
  DesktopMonitor,
  LogoLockup,
  Wordmark,
  IconGrid,
  TrustBadge,
  CompanyLogoRow,
  SocialProofRow,
  ProductCard,
  ProductGrid,
  CheckoutScreen,
  ShoppingCart,
  ReviewCard,
  RatingStars,
  BeforeAfterComparison,
  OfferStack,
  GuaranteeBox,
  LineChart,
  BarChart,
  PieChart,
  GrowthCurve,
  Timeline,
  Funnel,
  ProgressRing,
  Counter,
  AnimatedGraph,
  BookCoverCarousel,
  BookCoverStream,
  CourseCarousel,
  ImageStack,
  ScreenshotGallery,
  VideoThumbnail,
  FloatingMediaWall,
  ParticleField,
  GradientBlob,
  AnimatedGrid,
  OrbitalLines,
  FloatingShapes,
  NoiseOverlay,
  GlowField,
  MeshGradient,
  Aurora,
  BlueprintGrid,
  SequentialReveal,
  StaggerGrid,
  CardStack,
  InfiniteHorizontalCarousel,
  InfiniteVerticalCarousel,
  Marquee,
  FloatingLayerGroup,
  ExplodedLayout,
  IsometricStack,
  Capsule3D,
  PillHero,
};

for (const [id, component] of Object.entries(REGISTRY)) {
  registerMotionComponent(id, component);
}

export {
  MetricCard,
  PricingCard,
  FeatureCard,
  ChatWindow,
  Dashboard,
  iPhone,
  ClaudeMobileHome,
  LogoLockup,
  ProductCard,
  LineChart,
  BookCoverCarousel,
  ParticleField,
  Capsule3D,
  PillHero,
  StaggerGrid,
};
